wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1662424282.258461
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.7.13
      5: 0.13.1
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 32
is_constrained:
  desc: null
  value: false
n_iters:
  desc: null
  value: 1000
train_ratio:
  desc: null
  value: 0.6
unconst_lr:
  desc: null
  value: 0.001
